apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mnist-service
  name: mnist-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnist-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mnist-service
    spec:
      containers:
      - args:
        - --port=9000
        - --model_name=mnist-service
        - --model_base_path=/mnt/export
        command:
        - /usr/bin/tensorflow_model_server
        image: IMG
        imagePullPolicy: IfNotPresent
        name: mnist-service
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
        securityContext:
          procMount: Default
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30